version: "3.5"

networks:
  services:
    name: services
    driver: bridge

services:
  sumo:
    image: ubuntu:latest
    container_name: sumo
    ports:
      - "8086:8086"
    environment:
      - SUMO_HOME="/sumo"
      - PATH="/sumo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    command: ["bash", "/home/sumo_install_script.sh" ]
    volumes:
      - ./sumo:/home
